# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `rails
# db:schema:load`. When creating a new database, `rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2021_06_29_234659) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "especials", force: :cascade do |t|
    t.string "id_catastral"
    t.string "provincia"
    t.string "distrito"
    t.string "corregimiento"
    t.string "ejido"
    t.string "lugar"
    t.string "calle"
    t.string "localizacion"
    t.string "geo_point"
    t.string "n_mapa_catastral"
    t.string "n_ortofoto"
    t.string "n_predio"
    t.string "s_predial"
    t.string "nombre_predio"
    t.string "titulo_propiedad"
    t.string "ph"
    t.string "finca_ph"
    t.string "concesion_admin"
    t.string "litigio"
    t.string "tipo_de_litigio"
    t.string "finca"
    t.string "folio"
    t.string "docum"
    t.string "operacion"
    t.string "tomo"
    t.string "rollo"
    t.string "registro"
    t.string "asiento"
    t.date "fecha_del_titulo"
    t.date "fecha_de_registro"
    t.string "superficie_inscrita"
    t.string "finca_madre"
    t.string "otorgado"
    t.string "tipo_de_titulo"
    t.string "n_resolucion"
    t.date "fecha_resolucion"
    t.string "tipo_resolucion"
    t.string "n_de_orden"
    t.string "n_plano"
    t.string "globo"
    t.string "plano_de_referencia"
    t.string "sup_reportada"
    t.string "tipo_de_persona"
    t.string "sexo"
    t.string "cedula"
    t.integer "n_dependientes"
    t.string "nacionalidad"
    t.string "ocupacion"
    t.string "primer_nombre"
    t.string "segundo_nombre"
    t.string "primer_apellido"
    t.string "segundo_apellido"
    t.string "nombre_casada"
    t.string "nombre_usual"
    t.string "apellido_usual"
    t.string "organizacion"
    t.date "fecha_de_nacimiento"
    t.string "telefono"
    t.string "dirreccion"
    t.string "estado_civil"
    t.date "fecha_de_ocupacion"
    t.string "apartado"
    t.text "observaciones_ficha"
    t.string "empadronador_nombre"
    t.string "empadronador_firma"
    t.string "inspector_nombre"
    t.string "inspector_firma"
    t.string "supervisor_nombre"
    t.string "supervisor_firma"
    t.string "captador_nombre"
    t.string "captador_firma"
    t.string "empresa"
    t.string "metodologia"
    t.date "fecha_levantamiento"
    t.string "hora_levantamiento"
    t.string "equipo"
    t.string "verficado"
    t.string "firma_propietario"
    t.string "cedula_propetario"
    t.string "funcionario_firma"
    t.string "sustanciador_firma"
    t.string "topografia"
    t.string "pendiente_ap"
    t.boolean "agua"
    t.boolean "luz"
    t.boolean "x_none"
    t.string "tipo_de_construccion"
    t.string "uso_de_tierra"
    t.string "cercas_existentes"
    t.string "hidrigrafia"
    t.string "vias_de_acceso"
    t.string "servidumbre_de_acceso"
    t.string "servidumbre"
    t.string "n_manzanas"
    t.boolean "acera"
    t.boolean "acueductos"
    t.boolean "tuberia_gas"
    t.boolean "m_cordon"
    t.boolean "alcantarillado"
    t.boolean "telefono_m"
    t.boolean "m_luz"
    t.boolean "tv"
    t.boolean "senal_celular"
    t.boolean "sena_satelital"
    t.text "m_otro"
    t.boolean "uso_recidencial"
    t.boolean "uso_tuiristico"
    t.boolean "uso_comercial"
    t.boolean "uso_industrial"
    t.boolean "uso_educacioal"
    t.boolean "uso_recreacional"
    t.string "tipo_resindencial"
    t.string "paredes"
    t.string "estructura_techo"
    t.string "cubierta_techo"
    t.boolean "piso_cemento"
    t.boolean "piso_baldosa"
    t.boolean "piso_granito"
    t.boolean "piso_ceramica"
    t.boolean "piso_madera"
    t.boolean "piso_tierra"
    t.boolean "piso_otro"
    t.string "solo_agua"
    t.string "n_diseminados"
    t.string "n_servicio2"
    t.string "n_servicio3"
    t.string "electricidad"
    t.text "m_otro2"
    t.string "address"
    t.float "latitude"
    t.float "longitude"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "neighbors", force: :cascade do |t|
    t.string "name"
    t.string "id_number"
    t.string "estate"
    t.string "firma"
    t.bigint "rural_id", null: false
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["rural_id"], name: "index_neighbors_on_rural_id"
  end

  create_table "owners", force: :cascade do |t|
    t.date "fecha_oc"
    t.date "fecha_nac"
    t.string "p_nombre"
    t.string "s_nombre"
    t.string "p_apellido"
    t.string "s_apellido"
    t.string "c_apellido"
    t.string "nombre_u"
    t.string "organizacion"
    t.string "cedula"
    t.string "estado_c"
    t.string "telefono"
    t.string "apartado"
    t.string "ocupacion"
    t.string "dirreccion"
    t.string "firma"
    t.bigint "rural_id", null: false
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["rural_id"], name: "index_owners_on_rural_id"
  end

  create_table "rurals", force: :cascade do |t|
    t.string "id_catastral"
    t.string "provincia"
    t.string "distrito"
    t.string "corregimiento"
    t.string "ejido"
    t.string "lugar"
    t.string "calle"
    t.string "localizacion"
    t.string "geo_point"
    t.string "n_mapa_catastral"
    t.string "n_ortofoto"
    t.string "n_predio"
    t.string "s_predial"
    t.string "nombre_predio"
    t.string "titulo_propiedad"
    t.string "ph"
    t.string "finca_ph"
    t.string "concesion_admin"
    t.string "litigio"
    t.string "tipo_de_litigio"
    t.string "finca"
    t.string "folio"
    t.string "docum"
    t.string "operacion"
    t.string "tomo"
    t.string "rollo"
    t.string "registro"
    t.string "asiento"
    t.date "fecha_del_titulo"
    t.date "fecha_de_registro"
    t.string "superficie_inscrita"
    t.string "finca_madre"
    t.string "otorgado"
    t.string "tipo_de_titulo"
    t.string "n_resolucion"
    t.date "fecha_resolucion"
    t.string "tipo_resolucion"
    t.string "n_de_orden"
    t.string "n_plano"
    t.string "globo"
    t.string "plano_de_referencia"
    t.string "sup_reportada"
    t.string "tipo_de_persona"
    t.string "sexo"
    t.string "cedula"
    t.integer "n_dependientes"
    t.string "nacionalidad"
    t.string "ocupacion"
    t.string "primer_nombre"
    t.string "segundo_nombre"
    t.string "primer_apellido"
    t.string "segundo_apellido"
    t.string "nombre_casada"
    t.string "nombre_usual"
    t.string "apellido_usual"
    t.string "organizacion"
    t.date "fecha_de_nacimiento"
    t.string "telefono"
    t.string "dirreccion"
    t.string "estado_civil"
    t.date "fecha_de_ocupacion"
    t.string "apartado"
    t.string "topografia"
    t.string "pendiente_ap"
    t.boolean "agua"
    t.boolean "luz"
    t.boolean "x_none"
    t.string "tipo_de_construccion"
    t.string "del_propietario"
    t.string "de_otro"
    t.string "uso_de_tierra"
    t.string "cercas_existentes"
    t.string "hidrografia"
    t.string "vias_de_acceso"
    t.string "servidumbre_de_acceso"
    t.string "servidumbre"
    t.text "observaciones_ficha"
    t.string "empadronador_nombre"
    t.string "empadronador_firma"
    t.string "inspector_nombre"
    t.string "inspector_firma"
    t.string "supervisor_nombre"
    t.string "supervisor_firma"
    t.string "captador_nombre"
    t.string "captador_firma"
    t.string "empresa"
    t.string "metodologia"
    t.date "fecha_levantamiento"
    t.string "hora_levantamiento"
    t.string "equipo"
    t.string "verficado"
    t.string "firma_propietario"
    t.string "cedula_propetario"
    t.string "funcionario_firma"
    t.string "sustanciador_firma"
    t.bigint "user_id", null: false
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.float "latitude"
    t.float "longitude"
    t.string "address"
    t.index ["user_id"], name: "index_rurals_on_user_id"
  end

  create_table "urbanos", force: :cascade do |t|
    t.string "id_catastral"
    t.string "provincia"
    t.string "distrito"
    t.string "corregimiento"
    t.string "ejido"
    t.string "lugar"
    t.string "calle"
    t.string "localizacion"
    t.string "n_mapa_catastral"
    t.string "n_ortofoto"
    t.string "n_predio"
    t.string "s_predial"
    t.string "nombre_predio"
    t.string "titulo_propiedad"
    t.string "ph"
    t.string "finca_ph"
    t.string "concesion_admin"
    t.string "litigio"
    t.string "tipo_de_litigio"
    t.string "finca"
    t.string "folio"
    t.string "docum"
    t.string "operacion"
    t.string "tomo"
    t.string "rollo"
    t.string "registro"
    t.string "asiento"
    t.date "fecha_del_titulo"
    t.date "fecha_de_registro"
    t.string "superficie_inscrita"
    t.string "finca_madre"
    t.string "otorgado"
    t.string "tipo_de_titulo"
    t.string "n_resolucion"
    t.date "fecha_resolucion"
    t.string "tipo_resolucion"
    t.string "n_de_orden"
    t.string "n_plano"
    t.string "globo"
    t.string "plano_de_referencia"
    t.string "sup_reportada"
    t.string "tipo_de_persona"
    t.string "sexo"
    t.string "cedula"
    t.integer "n_dependientes"
    t.string "nacionalidad"
    t.string "ocupacion"
    t.string "primer_nombre"
    t.string "segundo_nombre"
    t.string "primer_apellido"
    t.string "segundo_apellido"
    t.string "nombre_casada"
    t.string "nombre_usual"
    t.string "apellido_usual"
    t.string "organizacion"
    t.date "fecha_de_nacimiento"
    t.string "telefono"
    t.string "dirreccion"
    t.string "estado_civil"
    t.date "fecha_de_ocupacion"
    t.string "apartado"
    t.text "observaciones_ficha"
    t.string "empadronador_nombre"
    t.string "empadronador_firma"
    t.string "inspector_nombre"
    t.string "inspector_firma"
    t.string "supervisor_nombre"
    t.string "supervisor_firma"
    t.string "captador_nombre"
    t.string "captador_firma"
    t.string "empresa"
    t.string "metodologia"
    t.date "fecha_levantamiento"
    t.string "hora_levantamiento"
    t.string "equipo"
    t.string "verficado"
    t.string "firma_propietario"
    t.string "cedula_propetario"
    t.string "funcionario_firma"
    t.string "sustanciador_firma"
    t.string "inclinacion"
    t.string "aprovechamiento"
    t.boolean "vivienda_t"
    t.boolean "comercial_t"
    t.boolean "industrial_t"
    t.boolean "turístico_t"
    t.boolean "educacional_t"
    t.boolean "uso_publico_t"
    t.boolean "comunal_t"
    t.boolean "agricola_t"
    t.boolean "ganadero_t"
    t.boolean "otro_t"
    t.string "vias_acesso"
    t.string "n_manzana"
    t.string "m_uso"
    t.boolean "cera"
    t.boolean "acueductos"
    t.boolean "tuberia_gas"
    t.boolean "m_cordon"
    t.boolean "alcantarillado"
    t.boolean "telefono_m"
    t.boolean "m_luz"
    t.boolean "tv"
    t.boolean "senal_celular"
    t.boolean "sena_satelital"
    t.text "m_otro"
    t.string "material_calle"
    t.boolean "uso_recidencial"
    t.boolean "uso_tuiristico"
    t.boolean "uso_industrial"
    t.boolean "uso_educacioal"
    t.boolean "uso_comercial"
    t.boolean "uso_recreacional"
    t.string "tipo_resindencial"
    t.string "paredes"
    t.string "estructura_techo"
    t.string "cubierta_techo"
    t.boolean "piso_cemento"
    t.boolean "piso_baldosa"
    t.boolean "piso_granito"
    t.boolean "piso_ceramica"
    t.boolean "piso_madera"
    t.boolean "piso_tierra"
    t.boolean "piso_otro"
    t.string "solo_agua"
    t.string "n_diseminados"
    t.string "n_servicio2"
    t.string "n_servicio3"
    t.string "electricidad"
    t.text "m_otro2"
    t.string "address"
    t.float "latitude"
    t.float "longitude"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.string "otp_secret_key"
    t.integer "otp_module"
    t.string "name"
    t.string "last_name"
    t.string "role"
    t.string "id_n"
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end

  add_foreign_key "neighbors", "rurals"
  add_foreign_key "owners", "rurals"
  add_foreign_key "rurals", "users"
end
