class CreateUrbanos < ActiveRecord::Migration[6.0]
  def change
    create_table :urbanos do |t|
      t.string :id_catastral
      t.string :provincia
      t.string :distrito
      t.string :corregimiento
      t.string :ejido
      t.string :lugar
      t.string :calle
      t.string :localizacion
      t.string :n_mapa_catastral
      t.string :n_ortofoto
      t.string :n_predio
      t.string :s_predial
      t.string :nombre_predio
      t.string :titulo_propiedad
      t.string :ph
      t.string :finca_ph
      t.string :concesion_admin
      t.string :litigio
      t.string :tipo_de_litigio
      t.string :finca
      t.string :folio
      t.string :docum
      t.string :operacion
      t.string :tomo
      t.string :rollo
      t.string :registro
      t.string :asiento
      t.date :fecha_del_titulo
      t.date :fecha_de_registro
      t.string :superficie_inscrita
      t.string :finca_madre
      t.string :otorgado
      t.string :tipo_de_titulo
      t.string :n_resolucion
      t.date :fecha_resolucion
      t.string :tipo_resolucion
      t.string :n_de_orden
      t.string :n_plano
      t.string :globo
      t.string :plano_de_referencia
      t.string :sup_reportada
      t.string :tipo_de_persona
      t.string :sexo
      t.string :cedula
      t.integer :n_dependientes
      t.string :nacionalidad
      t.string :ocupacion
      t.string :primer_nombre
      t.string :segundo_nombre
      t.string :primer_apellido
      t.string :segundo_apellido
      t.string :nombre_casada
      t.string :nombre_usual
      t.string :apellido_usual
      t.string :organizacion
      t.date :fecha_de_nacimiento
      t.string :telefono
      t.string :dirreccion
      t.string :estado_civil
      t.date :fecha_de_ocupacion
      t.string :apartado
      t.text :observaciones_ficha
      t.string :empadronador_nombre
      t.string :empadronador_firma
      t.string :inspector_nombre
      t.string :inspector_firma
      t.string :supervisor_nombre
      t.string :supervisor_firma
      t.string :captador_nombre
      t.string :captador_firma
      t.string :empresa
      t.string :metodologia
      t.date :fecha_levantamiento
      t.string :hora_levantamiento
      t.string :equipo
      t.string :verficado
      t.string :firma_propietario
      t.string :cedula_propetario
      t.string :funcionario_firma
      t.string :sustanciador_firma
      t.string :inclinacion
      t.string :aprovechamiento
      t.boolean :vivienda_t
      t.boolean :comercial_t
      t.boolean :industrial_t
      t.boolean :turístico_t
      t.boolean :educacional_t
      t.boolean :uso_publico_t
      t.boolean :comunal_t
      t.boolean :agricola_t
      t.boolean :ganadero_t
      t.boolean :otro_t
      t.string :vias_acesso
      t.string :n_manzana
      t.string :m_uso
      t.boolean :cera
      t.boolean :acueductos
      t.boolean :tuberia_gas
      t.boolean :m_cordon
      t.boolean :alcantarillado
      t.boolean :telefono_m
      t.boolean :m_luz
      t.boolean :tv
      t.boolean :senal_celular
      t.boolean :sena_satelital
      t.text :m_otro
      t.string :material_calle
      t.boolean :uso_recidencial
      t.boolean :uso_tuiristico
      t.boolean :uso_industrial
      t.boolean :uso_educacioal
      t.boolean :uso_comercial
      t.boolean :uso_recreacional
      t.string :tipo_resindencial
      t.string :paredes
      t.string :estructura_techo
      t.string :cubierta_techo
      t.boolean :piso_cemento
      t.boolean :piso_baldosa
      t.boolean :piso_granito
      t.boolean :piso_ceramica
      t.boolean :piso_madera
      t.boolean :piso_tierra
      t.boolean :piso_otro
      t.string :solo_agua
      t.string :n_diseminados
      t.string :n_servicio2
      t.string :n_servicio3
      t.string :electricidad
      t.text :m_otro2
      t.string :address
      t.float :latitude
      t.float :longitude

      t.timestamps
    end
  end
end
